package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CraClientes generated by hbm2java
 */
@Entity
@Table(name="cra_clientes"
    ,catalog="db_caio_ayala"
)
public class CraClientes  implements java.io.Serializable {


     private int craIdCliente;
     private String craNome;
     private String craCpf;
     private String craSenha;
     private String craTelefone;
     private String craNumeroDaCasa;
     private String craComplemento;
     private String craEmail;
     private String craEndereco;
     private String craCep;
     private String craDataNascimento;
     private String craCelular;
     private String craCidade;
     private String craEstado;
     private int craStatus;



    public CraClientes() {
    }

	
    public CraClientes(int craIdCliente, String craNome, String craCpf, String craSenha, String craEmail, String craEndereco, String craDataNascimento, String craCelular, String craCidade, String craEstado, int craStatus) {
        this.craIdCliente = craIdCliente;
        this.craNome = craNome;
        this.craCpf = craCpf;
        this.craSenha = craSenha;
        this.craEmail = craEmail;
        this.craEndereco = craEndereco;
        this.craDataNascimento = craDataNascimento;
        this.craCelular = craCelular;
        this.craCidade = craCidade;
        this.craEstado = craEstado;
        this.craStatus = craStatus;
    }
    public CraClientes(int craIdCliente, String craNome, String craCpf, String craSenha, String craTelefone, String craNumeroDaCasa, String craComplemento, String craEmail, String craEndereco, String craCep, String craDataNascimento, String craCelular, String craCidade, String craEstado, int craStatus, Set craVendases) {
       this.craIdCliente = craIdCliente;
       this.craNome = craNome;
       this.craCpf = craCpf;
       this.craSenha = craSenha;
       this.craTelefone = craTelefone;
       this.craNumeroDaCasa = craNumeroDaCasa;
       this.craComplemento = craComplemento;
       this.craEmail = craEmail;
       this.craEndereco = craEndereco;
       this.craCep = craCep;
       this.craDataNascimento = craDataNascimento;
       this.craCelular = craCelular;
       this.craCidade = craCidade;
       this.craEstado = craEstado;
       this.craStatus = craStatus;

    }
   
     @Id 

    
    @Column(name="cra_id_cliente", unique=true, nullable=false)
    public int getCraIdCliente() {
        return this.craIdCliente;
    }
    
    public void setCraIdCliente(int craIdCliente) {
        this.craIdCliente = craIdCliente;
    }

    
    @Column(name="cra_nome", nullable=false, length=50)
    public String getCraNome() {
        return this.craNome;
    }
    
    public void setCraNome(String craNome) {
        this.craNome = craNome;
    }

    
    @Column(name="cra_cpf", nullable=false, length=14)
    public String getCraCpf() {
        return this.craCpf;
    }
    
    public void setCraCpf(String craCpf) {
        this.craCpf = craCpf;
    }

    
    @Column(name="cra_senha", nullable=false, length=60)
    public String getCraSenha() {
        return this.craSenha;
    }
    
    public void setCraSenha(String craSenha) {
        this.craSenha = craSenha;
    }

    
    @Column(name="cra_telefone", length=45)
    public String getCraTelefone() {
        return this.craTelefone;
    }
    
    public void setCraTelefone(String craTelefone) {
        this.craTelefone = craTelefone;
    }

    
    @Column(name="cra_numeroDaCasa", length=20)
    public String getCraNumeroDaCasa() {
        return this.craNumeroDaCasa;
    }
    
    public void setCraNumeroDaCasa(String craNumeroDaCasa) {
        this.craNumeroDaCasa = craNumeroDaCasa;
    }

    
    @Column(name="cra_complemento", length=90)
    public String getCraComplemento() {
        return this.craComplemento;
    }
    
    public void setCraComplemento(String craComplemento) {
        this.craComplemento = craComplemento;
    }

    
    @Column(name="cra_email", nullable=false, length=60)
    public String getCraEmail() {
        return this.craEmail;
    }
    
    public void setCraEmail(String craEmail) {
        this.craEmail = craEmail;
    }

    
    @Column(name="cra_endereco", nullable=false, length=60)
    public String getCraEndereco() {
        return this.craEndereco;
    }
    
    public void setCraEndereco(String craEndereco) {
        this.craEndereco = craEndereco;
    }

    
    @Column(name="cra_cep", length=20)
    public String getCraCep() {
        return this.craCep;
    }
    
    public void setCraCep(String craCep) {
        this.craCep = craCep;
    }

    
    @Column(name="cra_dataNascimento", nullable=false, length=20)
    public String getCraDataNascimento() {
        return this.craDataNascimento;
    }
    
    public void setCraDataNascimento(String craDataNascimento) {
        this.craDataNascimento = craDataNascimento;
    }

    
    @Column(name="cra_celular", nullable=false, length=20)
    public String getCraCelular() {
        return this.craCelular;
    }
    
    public void setCraCelular(String craCelular) {
        this.craCelular = craCelular;
    }

    
    @Column(name="cra_cidade", nullable=false, length=30)
    public String getCraCidade() {
        return this.craCidade;
    }
    
    public void setCraCidade(String craCidade) {
        this.craCidade = craCidade;
    }

    
    @Column(name="cra_estado", nullable=false, length=30)
    public String getCraEstado() {
        return this.craEstado;
    }
    
    public void setCraEstado(String craEstado) {
        this.craEstado = craEstado;
    }

    
    @Column(name="cra_status", nullable=false)
    public int getCraStatus() {
        return this.craStatus;
    }
    
    public void setCraStatus(int craStatus) {
        this.craStatus = craStatus;
    }


}


