package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CraFuncionario generated by hbm2java
 */
@Entity
@Table(name="cra_funcionario"
    ,catalog="db_caio_ayala"
)
public class CraFuncionario  implements java.io.Serializable {
    private int idfuncionario;
    private String descricao;
    private String ativo;

    @Override
    public String toString() {
        return this.getCraNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof CraFuncionario) {
            CraFuncionario funcionario = (CraFuncionario) obj;
            return this.getCraIdFuncionario() == funcionario.getCraIdFuncionario();
        }
        return false;
    }

     private int craIdFuncionario;
     private String craNome;
     private String craCpf;
     private String craCargo;
     private String craCelular;
     private Double craSalario;
     private Date craDataAdmissao;


    public CraFuncionario() {
    }
     public CraFuncionario(int craIdFuncionario) {
        this.craIdFuncionario = craIdFuncionario;
    }

	
    public CraFuncionario(int craIdFuncionario, String craNome, String craCpf, String craCargo, String craCelular, Double craSalario) {
        this.craIdFuncionario = craIdFuncionario;
        this.craNome = craNome;
        this.craCpf = craCpf;
        this.craCargo = craCargo;
        this.craCelular = craCelular;
        this.craSalario = craSalario;
    }
    public CraFuncionario(int craIdFuncionario, String craNome, String craCpf, String craCargo, String craCelular, Double craSalario, Date craDataAdmissao, Set craVendases) {
       this.craIdFuncionario = craIdFuncionario;
       this.craNome = craNome;
       this.craCpf = craCpf;
       this.craCargo = craCargo;
       this.craCelular = craCelular;
       this.craSalario = craSalario;
       this.craDataAdmissao = craDataAdmissao;

    }
   
     @Id 

    
    @Column(name="cra_id_funcionario", unique=true, nullable=false)
    public int getCraIdFuncionario() {
        return this.craIdFuncionario;
    }
    
    public void setCraIdFuncionario(int craIdFuncionario) {
        this.craIdFuncionario = craIdFuncionario;
    }

    
    @Column(name="cra_nome", nullable=false, length=50)
    public String getCraNome() {
        return this.craNome;
    }
    
    public void setCraNome(String craNome) {
        this.craNome = craNome;
    }

    
    @Column(name="cra_cpf", nullable=false, length=14)
    public String getCraCpf() {
        return this.craCpf;
    }
    
    public void setCraCpf(String craCpf) {
        this.craCpf = craCpf;
    }

    
    @Column(name="cra_cargo", nullable=false, length=50)
    public String getCraCargo() {
        return this.craCargo;
    }
    
    public void setCraCargo(String craCargo) {
        this.craCargo = craCargo;
    }

    
    @Column(name="cra_celular", nullable=false, length=15)
    public String getCraCelular() {
        return this.craCelular;
    }
    
    public void setCraCelular(String craCelular) {
        this.craCelular = craCelular;
    }

    
    @Column(name="cra_salario", nullable=false, precision=10)
    public Double getCraSalario() {
        return this.craSalario;
    }
    
    public void setCraSalario(Double craSalario) {
        this.craSalario = craSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cra_dataAdmissao", length=10)
    public Date getCraDataAdmissao() {
        return this.craDataAdmissao;
    }
    
    public void setCraDataAdmissao(Date craDataAdmissao) {
        this.craDataAdmissao = craDataAdmissao;
    }


}


