package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CraProduto generated by hbm2java
 */
@Entity
@Table(name="cra_produto"
    ,catalog="db_caio_ayala"
)
public class CraProduto  implements java.io.Serializable {


     private int craIdProduto;
     private String craNome;
     private String craDescricao;
     private Double craPreco;
     private String craTamanho;
     private String craSabor;
     private String craDisponivel;


    public CraProduto() {
    }

	
    public CraProduto(int craIdProduto, String craNome, String craDescricao, Double craPreco, String craTamanho, String craSabor, String craDisponivel) {
        this.craIdProduto = craIdProduto;
        this.craNome = craNome;
        this.craDescricao = craDescricao;
        this.craPreco = craPreco;
        this.craTamanho = craTamanho;
        this.craSabor = craSabor;
        this.craDisponivel = craDisponivel;
    }
    public CraProduto(int craIdProduto, String craNome, String craDescricao, Double craPreco, String craTamanho, String craSabor, String craDisponivel, Set craVendasProdutoses) {
       this.craIdProduto = craIdProduto;
       this.craNome = craNome;
       this.craDescricao = craDescricao;
       this.craPreco = craPreco;
       this.craTamanho = craTamanho;
       this.craSabor = craSabor;
       this.craDisponivel = craDisponivel;

    }
   
     @Id 

    
    @Column(name="cra_id_produto", unique=true, nullable=false)
    public int getCraIdProduto() {
        return this.craIdProduto;
    }
    
    public void setCraIdProduto(int craIdProduto) {
        this.craIdProduto = craIdProduto;
    }

    
    @Column(name="cra_nome", nullable=false, length=45)
    public String getCraNome() {
        return this.craNome;
    }
    
    public void setCraNome(String craNome) {
        this.craNome = craNome;
    }

    
    @Column(name="cra_descricao", nullable=false, length=60)
    public String getCraDescricao() {
        return this.craDescricao;
    }
    
    public void setCraDescricao(String craDescricao) {
        this.craDescricao = craDescricao;
    }

    
    @Column(name="cra_preco", nullable=false, precision=10)
    public Double getCraPreco() {
        return this.craPreco;
    }
    
    public void setCraPreco(Double craPreco) {
        this.craPreco = craPreco;
    }

    
    @Column(name="cra_tamanho", nullable=false, length=2)
    public String getCraTamanho() {
        return this.craTamanho;
    }
    
    public void setCraTamanho(String craTamanho) {
        this.craTamanho = craTamanho;
    }

    
    @Column(name="cra_sabor", nullable=false, length=50)
    public String getCraSabor() {
        return this.craSabor;
    }
    
    public void setCraSabor(String craSabor) {
        this.craSabor = craSabor;
    }

    
    @Column(name="cra_disponivel", nullable=false, length=1)
    public String getCraDisponivel() {
        return this.craDisponivel;
    }
    
    public void setCraDisponivel(String craDisponivel) {
        this.craDisponivel = craDisponivel;
    }
    @Override 
    public String toString(){
        return this.craNome;
    }




}


