package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CraProduto generated by hbm2java
 */
@Entity
@Table(name="cra_produto"
    ,catalog="db_caio_ayala"
)
public class CraProduto  implements java.io.Serializable {


     private int craIdProduto;
     private String craNome;
     private String craDescricao;
     private BigDecimal craPreco;
     private String craTamanho;
     private String craSabor;
     private char craDisponivel;
     private Set craVendasProdutoses = new HashSet(0);

    public CraProduto() {
    }

	
    public CraProduto(int craIdProduto, String craNome, String craDescricao, BigDecimal craPreco, String craTamanho, String craSabor, char craDisponivel) {
        this.craIdProduto = craIdProduto;
        this.craNome = craNome;
        this.craDescricao = craDescricao;
        this.craPreco = craPreco;
        this.craTamanho = craTamanho;
        this.craSabor = craSabor;
        this.craDisponivel = craDisponivel;
    }
    public CraProduto(int craIdProduto, String craNome, String craDescricao, BigDecimal craPreco, String craTamanho, String craSabor, char craDisponivel, Set craVendasProdutoses) {
       this.craIdProduto = craIdProduto;
       this.craNome = craNome;
       this.craDescricao = craDescricao;
       this.craPreco = craPreco;
       this.craTamanho = craTamanho;
       this.craSabor = craSabor;
       this.craDisponivel = craDisponivel;
       this.craVendasProdutoses = craVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="cra_id_produto", unique=true, nullable=false)
    public int getCraIdProduto() {
        return this.craIdProduto;
    }
    
    public void setCraIdProduto(int craIdProduto) {
        this.craIdProduto = craIdProduto;
    }

    
    @Column(name="cra_nome", nullable=false, length=45)
    public String getCraNome() {
        return this.craNome;
    }
    
    public void setCraNome(String craNome) {
        this.craNome = craNome;
    }

    
    @Column(name="cra_descricao", nullable=false, length=60)
    public String getCraDescricao() {
        return this.craDescricao;
    }
    
    public void setCraDescricao(String craDescricao) {
        this.craDescricao = craDescricao;
    }

    
    @Column(name="cra_preco", nullable=false, precision=10)
    public BigDecimal getCraPreco() {
        return this.craPreco;
    }
    
    public void setCraPreco(BigDecimal craPreco) {
        this.craPreco = craPreco;
    }

    
    @Column(name="cra_tamanho", nullable=false, length=2)
    public String getCraTamanho() {
        return this.craTamanho;
    }
    
    public void setCraTamanho(String craTamanho) {
        this.craTamanho = craTamanho;
    }

    
    @Column(name="cra_sabor", nullable=false, length=50)
    public String getCraSabor() {
        return this.craSabor;
    }
    
    public void setCraSabor(String craSabor) {
        this.craSabor = craSabor;
    }

    
    @Column(name="cra_disponivel", nullable=false, length=1)
    public char getCraDisponivel() {
        return this.craDisponivel;
    }
    
    public void setCraDisponivel(char craDisponivel) {
        this.craDisponivel = craDisponivel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="craProduto")
    public Set getCraVendasProdutoses() {
        return this.craVendasProdutoses;
    }
    
    public void setCraVendasProdutoses(Set craVendasProdutoses) {
        this.craVendasProdutoses = craVendasProdutoses;
    }




}


