package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CraVendas generated by hbm2java
 */
@Entity
@Table(name="cra_vendas"
    ,catalog="db_caio_ayala"
)
public class CraVendas  implements java.io.Serializable {


     private int craIdVendas;
     private CraClientes craClientes;
     private CraFuncionario craFuncionario;
     private Date craDataVenda;
     private String craFormaPagamento;
     private Double craValorUnitario;
     private String craStatus;


    public CraVendas() {
    }

	
    public CraVendas(int craIdVendas) {
        this.craIdVendas = craIdVendas;
    }
    public CraVendas(int craIdVendas, CraClientes craClientes, CraFuncionario craFuncionario, Date craDataVenda, String craFormaPagamento, Double craValorUnitario, String craStatus, Set craVendasProdutoses) {
       this.craIdVendas = craIdVendas;
       this.craClientes = craClientes;
       this.craFuncionario = craFuncionario;
       this.craDataVenda = craDataVenda;
       this.craFormaPagamento = craFormaPagamento;
       this.craValorUnitario = craValorUnitario;
       this.craStatus = craStatus;

    }
   
     @Id 

    
    @Column(name="cra_id_vendas", unique=true, nullable=false)
    public int getCraIdVendas() {
        return this.craIdVendas;
    }
    
    public void setCraIdVendas(int craIdVendas) {
        this.craIdVendas = craIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cra_fk_clientes")
    public CraClientes getCraClientes() {
        return this.craClientes;
    }
    
    public void setCraClientes(CraClientes craClientes) {
        this.craClientes = craClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cra_fk_funcionario")
    public CraFuncionario getCraFuncionario() {
        return this.craFuncionario;
    }
    
    public void setCraFuncionario(CraFuncionario craFuncionario) {
        this.craFuncionario = craFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cra_dataVenda", length=10)
    public Date getCraDataVenda() {
        return this.craDataVenda;
    }
    
    public void setCraDataVenda(Date craDataVenda) {
        this.craDataVenda = craDataVenda;
    }

    
    @Column(name="cra_formaPagamento", length=45)
    public String getCraFormaPagamento() {
        return this.craFormaPagamento;
    }
    
    public void setCraFormaPagamento(String craFormaPagamento) {
        this.craFormaPagamento = craFormaPagamento;
    }

    
    @Column(name="cra_valorUnitario", precision=10)
    public Double getCraValorUnitario() {
        return this.craValorUnitario;
    }
    
    public void setCraValorUnitario(Double craValorUnitario) {
        this.craValorUnitario = craValorUnitario;
    }

    
    @Column(name="cra_status", length=50)
    public String getCraStatus() {
        return this.craStatus;
    }
    
    public void setCraStatus(String craStatus) {
        this.craStatus = craStatus;
    }


}


