package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CraVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="cra_vendas_produtos"
    ,catalog="db_caio_ayala"
)
public class CraVendasProdutos  implements java.io.Serializable {


     private int craIdVendasProdutos;
     private CraProduto craProduto;
     private CraVendas craVendas;
     private int craQuantidade;
     private Double craDesconto;
     private String craObservacao;
     private Double craPrecoFinal;

    public CraVendasProdutos() {
    }

    public CraVendasProdutos(int craIdVendasProdutos, CraProduto craProduto, CraVendas craVendas, int craQuantidade, Double craDesconto, String craObservacao, Double craPrecoFinal) {
       this.craIdVendasProdutos = craIdVendasProdutos;
       this.craProduto = craProduto;
       this.craVendas = craVendas;
       this.craQuantidade = craQuantidade;
       this.craDesconto = craDesconto;
       this.craObservacao = craObservacao;
       this.craPrecoFinal = craPrecoFinal;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="cra_id_vendas_produtos", unique=true, nullable=false)
    public int getCraIdVendasProdutos() {
        return this.craIdVendasProdutos;
    }
    
    public void setCraIdVendasProdutos(int craIdVendasProdutos) {
        this.craIdVendasProdutos = craIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cra_fk_produto", nullable=false)
    public CraProduto getCraProduto() {
        return this.craProduto;
    }
    
    public void setCraProduto(CraProduto craProduto) {
        this.craProduto = craProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cra_fk_venda", nullable=false)
    public CraVendas getCraVendas() {
        return this.craVendas;
    }
    
    public void setCraVendas(CraVendas craVendas) {
        this.craVendas = craVendas;
    }

    
    @Column(name="cra_quantidade", nullable=false)
    public int getCraQuantidade() {
        return this.craQuantidade;
    }
    
    public void setCraQuantidade(int craQuantidade) {
        this.craQuantidade = craQuantidade;
    }

    
    @Column(name="cra_desconto", nullable=false, precision=5)
    public Double getCraDesconto() {
        return this.craDesconto;
    }
    
    public void setCraDesconto(Double craDesconto) {
        this.craDesconto = craDesconto;
    }

    
    @Column(name="cra_observacao", nullable=false, length=200)
    public String getCraObservacao() {
        return this.craObservacao;
    }
    
    public void setCraObservacao(String craObservacao) {
        this.craObservacao = craObservacao;
    }

    
    @Column(name="cra_precoFinal", nullable=false, precision=10)
    public Double getCraPrecoFinal() {
        return this.craPrecoFinal;
    }
    
    public void setCraPrecoFinal(Double craPrecoFinal) {
        this.craPrecoFinal = craPrecoFinal;
    }




}


