package bean;
// Generated 12/10/2025 19:55:43 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrsUsuarios generated by hbm2java
 */
@Entity
@Table(name = "crs_usuarios",
         catalog = "db_caio_ayala"
)
public class CrsUsuarios implements java.io.Serializable {

    private int craIdUsuarios;
    private String craNome;
    private String craApelido;
    private String craCpf;
    private Date craDataNascimento;
    private String craSenha;
    private int craNivel;
    private String craAtivo;

    public CrsUsuarios() {
    }

    public CrsUsuarios(int craIdUsuarios, String craNome, String craCpf, Date craDataNascimento, String craSenha, int craNivel, String craAtivo) {
        this.craIdUsuarios = craIdUsuarios;
        this.craNome = craNome;
        this.craCpf = craCpf;
        this.craDataNascimento = craDataNascimento;
        this.craSenha = craSenha;
        this.craNivel = craNivel;
        this.craAtivo = craAtivo;
    }

    public CrsUsuarios(int craIdUsuarios, String craNome, String craApelido, String craCpf, Date craDataNascimento, String craSenha, int craNivel, String craAtivo) {
        this.craIdUsuarios = craIdUsuarios;
        this.craNome = craNome;
        this.craApelido = craApelido;
        this.craCpf = craCpf;
        this.craDataNascimento = craDataNascimento;
        this.craSenha = craSenha;
        this.craNivel = craNivel;
        this.craAtivo = craAtivo;
    }

    @Id

    @Column(name = "cra_id_usuarios", unique = true, nullable = false)
    public int getCraIdUsuarios() {
        return this.craIdUsuarios;
    }

    public void setCraIdUsuarios(int craIdUsuarios) {
        this.craIdUsuarios = craIdUsuarios;
    }

    @Column(name = "cra_nome", nullable = false, length = 50)
    public String getCraNome() {
        return this.craNome;
    }

    public void setCraNome(String craNome) {
        this.craNome = craNome;
    }

    @Column(name = "cra_apelido", length = 50)
    public String getCraApelido() {
        return this.craApelido;
    }

    public void setCraApelido(String craApelido) {
        this.craApelido = craApelido;
    }

    @Column(name = "cra_cpf", nullable = false, length = 14)
    public String getCraCpf() {
        return this.craCpf;
    }

    public void setCraCpf(String craCpf) {
        this.craCpf = craCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "cra_dataNascimento", nullable = true)
    public Date getCraDataNascimento() {
        return this.craDataNascimento;
    }

    public void setCraDataNascimento(Date craDataNascimento) {
        this.craDataNascimento = craDataNascimento;
    }

    @Column(name = "cra_senha", nullable = false, length = 45)
    public String getCraSenha() {
        return this.craSenha;
    }

    public void setCraSenha(String craSenha) {
        this.craSenha = craSenha;
    }

    @Column(name = "cra_nivel", nullable = false)
    public int getCraNivel() {
        return this.craNivel;
    }

    public void setCraNivel(int craNivel) {
        this.craNivel = craNivel;
    }

    @Column(name = "cra_ativo", nullable = false, length = 1)
    public String getCraAtivo() {
        return this.craAtivo;
    }

    public void setCraAtivo(String craAtivo) {
        this.craAtivo = craAtivo;
    }

}
